# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(608, 900)
        MainWindow.setMinimumSize(QtCore.QSize(608, 900))
        MainWindow.setMaximumSize(QtCore.QSize(608, 900))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_header = QtWidgets.QLabel(self.centralwidget)
        self.label_header.setGeometry(QtCore.QRect(0, 10, 611, 61))
        self.label_header.setObjectName("label_header")
        self.label_enterad = QtWidgets.QLabel(self.centralwidget)
        self.label_enterad.setGeometry(QtCore.QRect(0, 70, 611, 20))
        self.label_enterad.setObjectName("label_enterad")
        self.label_enterad_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_enterad_2.setGeometry(QtCore.QRect(0, 290, 611, 20))
        self.label_enterad_2.setObjectName("label_enterad_2")
        self.label_enterad_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_enterad_3.setGeometry(QtCore.QRect(0, 200, 611, 81))
        self.label_enterad_3.setObjectName("label_enterad_3")
        self.pushButton_submit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_submit.setGeometry(QtCore.QRect(140, 140, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_submit.setFont(font)
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.label_enterad_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_enterad_4.setGeometry(QtCore.QRect(0, 370, 611, 20))
        self.label_enterad_4.setObjectName("label_enterad_4")
        self.pushButton_roots = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_roots.setGeometry(QtCore.QRect(80, 700, 75, 41))
        self.pushButton_roots.setObjectName("pushButton_roots")
        self.pushButton_vertex = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_vertex.setGeometry(QtCore.QRect(260, 700, 75, 41))
        self.pushButton_vertex.setObjectName("pushButton_vertex")
        self.pushButton_factor = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_factor.setGeometry(QtCore.QRect(450, 700, 75, 41))
        self.pushButton_factor.setObjectName("pushButton_factor")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(490, 102, 91, 31))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.label_input = QtWidgets.QLabel(self.centralwidget)
        self.label_input.setGeometry(QtCore.QRect(176, 310, 261, 51))
        self.label_input.setObjectName("label_input")
        self.label_graph = QtWidgets.QLabel(self.centralwidget)
        self.label_graph.setGeometry(QtCore.QRect(86, 410, 431, 271))
        self.label_graph.setObjectName("label_graph")
        self.label_computation = QtWidgets.QLabel(self.centralwidget)
        self.label_computation.setGeometry(QtCore.QRect(10, 780, 581, 51))
        self.label_computation.setObjectName("label_computation")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(140, 100, 321, 31))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project 2"))
        self.label_header.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">The Parabolanalyzer</span><span style=\" font-size:16pt; font-weight:600; vertical-align:super;\">TM</span></p></body></html>"))
        self.label_enterad.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Enter in the equation of a parabola to analyze!</span></p></body></html>"))
        self.label_enterad_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Input:</span></p></body></html>"))
        self.label_enterad_3.setText(_translate("MainWindow", ""))
        self.pushButton_submit.setText(_translate("MainWindow", "Submit"))
        self.label_enterad_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Graph:</span></p></body></html>"))
        self.pushButton_roots.setText(_translate("MainWindow", "Roots"))
        self.pushButton_vertex.setText(_translate("MainWindow", "Vertex"))
        self.pushButton_factor.setText(_translate("MainWindow", "Factor"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear all"))
        self.label_input.setText(_translate("MainWindow", ""))
        self.label_graph.setText(_translate("MainWindow", ""))
        self.label_computation.setText(_translate("MainWindow", ""))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
